CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID TEXT,
    PRODUCT_NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY_ID TEXT,
    UNIT_TEXT ,
    PRICE_REAL
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, SUPPLIER_ID, CATEGORY_ID, UNIT_TEXT, PRICE_REAL) VALUES
('1', 'CHAIS', '1', '1', '10 BOXES*20BAGS', 18),
('2', 'CHANG', '1', '1', '5 24-12 OZ BOTTLES', 19),
('3', 'ANISEED SYRUP', '1', '2', '12-550 ML BOTTLES', 10),
('4', 'CHEFANTON SEASONING', '2', '2', '48-6 OZ JARS', 22),
('5', 'CHEF ANTON MIX', '2', '2', '36 BOXES', 21.35),
('6', 'CHOCOLATE BISCUITS', '3', '3', '10 PKGS', 12.75),
('7', 'CHOCOLATE CAKE MIX', '3', '3', '24 PKGS', 15.5),
('8', 'CHOCOLATE FUDGE', '4', '4', '12-100 G PKGS', 9.5),
('9', 'CHOCOLATE TRUFFLES', '4', '4', '24 PKGS', 11.25),
('10', 'CHOCOLATE COVERED ALMONDS', '5', '5', '12-200 G PKGS', 14.75);

SELECT COUNT(PRODUCT_ID) AS PRODUCT_COUNT
FROM PRODUCTS;

SELECT AVG(PRICE_REAL) AS AVERAGE_PRICE
FROM PRODUCTS;

SELECT SUM(PRICE_REAL) AS TOTAL_PRICE
FROM PRODUCTS;